### ISSUE TITLE
NS_ERROR_DOM_SECURITY_ERR

### ISSUE THREAD

**Issue by charleslbryant** [madrobby/dom-monster#17]
Error [Exception... "Security error" code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)" location: "http://mir.aculo.us/dom-monster/dommonster.js?14987 Line: 252"] while analyzing page.

Analyzing - http://www.web.com
Browser - Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6 GTB7.1 ( .NET CLR 3.5.30729; .NET4.0E)

Let me know if you need more info.

**Comment by madrobby** [comment]
Seems like you're on some older version of Firefox? I've tried with Firefox 3.6.13 Gecko/20101203 and all works good. Is this reproducible?

**Comment by charleslbryant** [comment]
I am no longer at the workstation this occurred on, but it is doing the same thing on my home computer which has that same version of Firefox you used. 

Did you try analyzing the same website, http://www.web.com?

dom monster booklet v1.2.2 

Error: Error [Exception... "Security error" code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)" location: "http://mir.aculo.us/dom-monster/dommonster.js?14987 Line: 252"] while analyzing page. Please let the DOM Monster know about this problem!

Browser: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13

**Comment by mpiva** [comment]
Got the same problem with Mozilla Firefox 3.5.9
(UA: Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.9.1.9) Gecko/20100315 Firefox/3.5.9 ( .NET CLR 3.5.30729)) and Mozilla Firefox 3.5.16
(UA: Mozilla/5.0 (Windows; U; Windows NT 5.1; it; rv:1.9.1.16) Gecko/20101130 Firefox/3.5.16 ( .NET CLR 3.5.30729))

Hope this helps.

MP

**Comment by karfau** [comment]
looks like another occurence:
Error [Exception... "Security error" code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)" location: "http://mir.aculo.us/dom-monster/dommonster.js?14991 Line: 252"] while analyzing page.
(not sure about the 14991)

the page was http://www.gmx.net/

my browser: Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13 (.NET CLR 3.5.30729)
(I have a lot of plugins installed...)

The same page with Google Chrome 8.0.552.237 brings up another result:
Error TypeError: Cannot read property 'length' of null while analyzing page.

With Opera 11 alias
Opera/9.80 (Windows NT 5.1; U; de) Presto/2.7.62 Version/11.00
the problem is yet another:
Error ReferenceError: Security error: attempted to read protected variable while analyzing page.

Hope it helps, cool bookmarklet, keep going

**Comment by jamesduncombe** [comment]
I have the same error:

Error [Exception... "Security error" code: "1000" nsresult: "0x805303e8 (NS_ERROR_DOM_SECURITY_ERR)" location: "http://mir.aculo.us/dom-monster/dommonster.js?14991 Line: 252"] while analyzing page.

For page: http://trentwalton.com/2010/08/24/dont-make-me-wait/

Browser:
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13

Hope this helps,

Cheers,

James

**Comment by charleslbryant** [comment]
When I tried the version I forked today I do not see this error. The version on http://mir.aculo.us/dom-monster/ still has the error.

**Comment by madrobby** [comment]
Seems we might be a bit out of luck, at least on Firefox. http://www.mrclay.org/2008/09/06/case-of-the-ns_error_dom_security_err/

**Comment by charleslbryant** [comment]
How about a try/catch to insulate this issue to allow the code to keep working instead of the nasty error?

I can update my fork and send you an update if you'd like.

**Comment by madrobby** [comment]
Charles: but that's exactly what we do, we wrap everything in a try/catch and just let the specific error fail, continuing on with others. :) of course, welcome any patches!
